#include "stm32f10x.h"
#include "gpio_macro.h"

#ifdef __cplusplus
extern "C"
#endif
	
#define LED_BLUE_GPIO	  GPIOC
#define LED_BLUE_PIN	  8
#define SW_USER_GPIO	  GPIOA
#define SW_USER_PIN		  0
	
volatile uint32_t	dly;


//lesson 3 timer
int main(void)
{
	RCC->APB2ENR |= RCC_APB2ENR_IOPAEN | RCC_APB2ENR_IOPCEN;
	RCC->APB1ENR |= RCC_APB1ENR_TIM3EN;
	
#if (LED_BLUE_PIN > 7)
	LED_BLUE_GPIO->CRH = (LED_BLUE_GPIO->CRH & CONFMASKH(LED_BLUE_PIN)) | GPIOPINCONFH(LED_BLUE_PIN, GPIOCONF(GPIO_MODE_OUTPUT2MHz, GPIO_CNF_OUTPUT_PUSHPULL));
#else
	LED_BLUE_GPIO->CRL = (LED_BLUE_GPIO->CRL & CONFMASKL(LED_BLUE_PIN)) | GPIOPINCONFL(LED_BLUE_PIN, GPIOCONF(GPIO_MODE_OUTPUT2MHz, GPIO_CNF_OUTPUT_PUSHPULL));
#endif
		
	TIM3->PSC = 7999; 	     // Set prescaler to 8 000 (PSC + 1)
	TIM3->ARR = 1000; 	      // Auto reload value 1000
	TIM3->CR1 = TIM_CR1_CEN; // Enable timer
	
	
	for (;;)
	{
		if (TIM3->SR & TIM_SR_UIF)
		{
			TIM3->SR &= ~TIM_SR_UIF;
			LED_BLUE_GPIO->ODR ^= (1 << LED_BLUE_PIN);
		}
	}
	
}


//lesson 2 read button
//int main(void)
//{
//	RCC->APB2ENR |= RCC_APB2ENR_IOPAEN | RCC_APB2ENR_IOPCEN;
//	
//	
//#if (LED_BLUE_PIN > 7)
//	LED_BLUE_GPIO->CRH = (LED_BLUE_GPIO->CRH & CONFMASKH(LED_BLUE_PIN)) | GPIOPINCONFH(LED_BLUE_PIN, GPIOCONF(GPIO_MODE_OUTPUT2MHz, GPIO_CNF_OUTPUT_PUSHPULL));
//#else
//	LED_BLUE_GPIO->CRL = (LED_BLUE_GPIO->CRL & CONFMASKL(LED_BLUE_PIN)) | GPIOPINCONFL(LED_BLUE_PIN, GPIOCONF(GPIO_MODE_OUTPUT2MHz, GPIO_CNF_OUTPUT_PUSHPULL));
//#endif
//	
//#if (SW_USER_PIN > 7)
//	SW_USER_GPIO->CRH	=	(SW_USER_GPIO->CRH & CONFMASKH(SW_USER_PIN)) | GPIOPINCONFH(SW_USER_PIN, GPIOCONF(GPIO_MODE_INPUT, GPIO_CNF_INPUT_FLOATING));
//#else
//	SW_USER_GPIO->CRL	=	(SW_USER_GPIO->CRH & CONFMASKL(SW_USER_PIN)) | GPIOPINCONFL(SW_USER_PIN, GPIOCONF(GPIO_MODE_INPUT, GPIO_CNF_INPUT_FLOATING));
//#endif
//	
//	for (;;)
//	{
//		if (SW_USER_GPIO->IDR & (1 << SW_USER_PIN))
//			LED_BLUE_GPIO->BSRR = (1 << LED_BLUE_PIN); 
//		else
//			LED_BLUE_GPIO->BRR = (1 << LED_BLUE_PIN);
//	}
//	
//}

//lesson 1 blink led
//int main(void)
//{
//	RCC->APB2ENR |= RCC_APB2ENR_IOPCEN; // enable portc clock
//
//#if (LED_BLUE_PIN > 7)
//  LED_BLUE_GPIO->CRH = (LED_BLUE_GPIO->CRH & CONFMASKH(LED_BLUE_PIN)) | GPIOPINCONFH(LED_BLUE_PIN, GPIOCONF(GPIO_MODE_OUTPUT2MHz, GPIO_CNF_OUTPUT_PUSHPULL));
//#else
//	LED_BLUE_GPIO->CRL = (LED_BLUE_GPIO->CRL & CONFMASKL(LED_BLUE_PIN)) | GPIOPINCONFL(LED_BLUE_PIN, GPIOCONF(GPIO_MODE_OUTPUT2MHz, GPIO_CNF_OUTPUT_PUSHPULL));
//#endif	
//
//	for (;;)
//	{
//		for (dly = 0; dly < 300000; dly++) ;
//		LED_BLUE_GPIO->BSRR = (1 << LED_BLUE_PIN);
//		for (dly = 0; dly < 300000; dly++) ;
//		LED_BLUE_GPIO->BRR = (1 << LED_BLUE_PIN);
//	}
//}
